FROM eclipse-temurin:21-jdk

RUN apt-get update && \
    apt-get install -y krb5-user mariadb-client maven software-properties-common && \
    apt-get update && \
    apt-get install -y  mariadb-plugin-gssapi-client && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /jdbc
