FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y krb5-kdc krb5-admin-server krb5-user && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY krb5.conf /etc/krb5.conf

COPY setup-kdc.sh /setup-kdc.sh
RUN chmod +x /setup-kdc.sh

ENTRYPOINT ["/setup-kdc.sh"]
