Krb5ConnectorContext {
    com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true
    storeKey=true
    keyTab="/keytabs/client.keytab"
    principal="test_krb_user@S2.TEST"
    debug=true
    doNotPrompt=true;
};

CustomKrbEntry {
    com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true
    storeKey=true
    keyTab="/keytabs/client.keytab"
    principal="test_krb_user@S2.TEST"
    debug=true
    doNotPrompt=true;
};
