[libdefaults]
    default_realm = S2.TEST
    dns_lookup_realm = false
    dns_lookup_kdc = false
    forwardable = true
    rdns = false
    ticket_lifetime = 24h
    renew_lifetime = 7d

[realms]
    S2.TEST = {
        kdc = kdc.s2.test
        admin_server = kdc.s2.test
    }

[domain_realm]
    .s2.test = S2.TEST
    s2.test = S2.TEST
